version: '3.8'

services:
  nextjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp_chatbot_frontend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - RAG_SERVICE_URL=http://python_rag:8000
    depends_on:
      - python_rag

  python_rag:
    build:
      context: ./rag_service
      dockerfile: Dockerfile
    container_name: whatsapp_chatbot_rag
    restart: always
    ports:
      - "8001:8000"
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - QWEN_API_KEY=${QWEN_API_KEY}
